name: footy
description: football standings app
publish_to: 'none'


version: 1.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  loading_animation_widget: ^1.1.0+3
  flutter_native_splash: ^2.1.1
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#445E93"
  image: "assets/images/backLayer.png"